Add ffmpeg-full
flathub/com.unity.UnityHub pull request #118
Opened 2024-01-28 15:00 UTC by rafaelhipercg

i fixed the ffmpeg error #94 adding the full ffmpeg module. now Wav files imported correctly on the Webgl

2024-02-07 13:59 UTC, DekosAnjo commented
@wjt @cassidyjames can you merge this?

2024-02-08 12:04 UTC, wjt commented
bot, build

2024-02-08 12:12 UTC, wjt requested changes

2024-02-08 12:12 UTC, wjt commented on com.unity.UnityHub.yaml
> +    add-ld-path: .
I don't think we need the 32-bit version. From #94, Unity invokes whatever `ffmpeg` is in the path, and the one in the path is the 64-bit version at `/usr/bin/ffmpeg`.

Plus, the given `directory`, `lib32/ffmpeg`, does not exist in `/app`. So at best, defining this extension has no effect; and at worst, if the extension is installed the app may fail to start. (I don't know what Flatpak does if the target directory for an extension is missing.)

```suggestion
```

2024-02-08 14:12 UTC, wjt approved these changes
Thanks!

2024-02-08 14:12 UTC, merged